//PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_MOST_POPULAR_PRODUCTS = "GET_MOST_POPULAR_PRODUCTS"

//CUSTOMERS
export const GET_CUSTOMER_INFO = "GET_CUSTOMER_INFO"
export const GET_CUSTOMER_MORE_INFO = "GET_CUSTOMER_MORE_INFO"

//USERS
export const GET_CURRENT_USER = "GET_CURRENT_USER"