//PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_MOST_POPULAR_PRODUCTS = "GET_MOST_POPULAR_PRODUCTS";
export const GET_PRODUCT_CATEGORIES = "GET_PRODUCT_CATEGORIES";
export const GET_MENUS = "GET_MENUS";
export const GET_MENU_OPTIONS = "GET_MENU_OPTIONS";
export const GET_MATERIALS = "GET_MATERIALS";

//ORDERS
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
export const CREATE_ORDER_DETAIL = "CREATE_ORDER_DETAIL";
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";

//CUSTOMERS
export const GET_CUSTOMER_INFO = "GET_CUSTOMER_INFO";
export const GET_CUSTOMER_MORE_INFO = "GET_CUSTOMER_MORE_INFO";
export const GET_CUSTOMER_SLIDER = "GET_CUSTOMER_SLIDER";
export const GET_CUSTOMER_GALERY = "GET_CUSTOMER_GALERY";
export const GET_CUSTOMER_CUISINES = "GET_CUSTOMER_CUISINES";

//REZERVATION
export const ADD_REZERVATION_SUCCESS = "ADD_REZERVATION_SUCCESS";
export const ADD_REZERVATION_FAIL = "ADD_REZERVATION_FAIL";

//COMMENTS
export const GET_CUSTOMERS_COMMENTS = "GET_CUSTOMERS_COMMENTS";
export const ADD_CUSTOMER_COMMENT = "ADD_CUSTOMER_COMMENT";
export const UPDATE_CUSTOMER_COMMENT = "UPDATE_CUSTOMER_COMMENT";

//COMMENT_LIKE
export const GET_CUSTOMER_COMMENT_LIKE = "GET_CUSTOMER_COMMENT_LIKE";
export const ADD_CUSTOMER_COMMENT_LIKE = "ADD_CUSTOMER_COMMENT_LIKE";
export const UPDATE_CUSTOMER_COMMENT_LIKE = "UPDATE_CUSTOMER_COMMENT_LIKE";
export const DELETE_CUSTOMER_COMMENT_LIKE = "DELETE_CUSTOMER_COMMENT_LIKE";

//USERS
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const ADD_FAVORITE_PRODUCT = "ADD_FAVORITE_PRODUCT";
export const DELETE_FAVORITE_PRODUCT = "DELETE_FAVORITE_PRODUCT";
export const GET_FAVORITE_PRODUCTS = "GET_FAVORITE_PRODUCTS";
export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAIL = "UPDATE_USER_INFO_FAIL";

//ADRESSES
export const GET_USER_ADDRESSES = "GET_USER_ADDRESSES";
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS";
export const CREATE_USER_ADDRESS_FAIL = "CREATE_USER_ADDRESS_FAIL";
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS";
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";

//CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_MENU_TO_CART = "ADD_MENU_TO_CART";
export const REMOVE_MENU_FROM_CART = "REMOVE_MENU_FROM_CART";
export const REMOVE_CART = "REMOVE_CART";
