const CustomerActionTypes = {
  FETCH_CUSTOMER_INFO_START: "FETCH_CUSTOMER_INFO_START",
  FETCH_CUSTOMER_INFO_SUCCESS: "FETCH_CUSTOMER_INFO_SUCCESS",
  FETCH_CUSTOMER_INFO_FAILURE: "FETCH_CUSTOMER_INFO_FAILURE",

  FETCH_CUSTOMER_MORE_INFO_START: "FETCH_CUSTOMER_MORE_INFO_START",
  FETCH_CUSTOMER_MORE_INFO_SUCCESS: "FETCH_CUSTOMER_MORE_INFO_SUCCESS",

  FETCH_CUSTOMER_SLIDER_START: "FETCH_CUSTOMER_SLIDER_START",
  FETCH_CUSTOMER_SLIDER_SUCCESS: "FETCH_CUSTOMER_SLIDER_SUCCESS",

  FETCH_CUSTOMER_GALLERY_START: "FETCH_CUSTOMER_GALLERY_START",
  FETCH_CUSTOMER_GALLERY_SUCCESS: "FETCH_CUSTOMER_GALLERY_SUCCESS",
};
export default CustomerActionTypes;
