const CustomerActionTypes = {
  CHANGE_CUSTOMER_ID: "CHANGE_CUSTOMER_ID",

  FETCH_CUSTOMER_INFO_START: "FETCH_CUSTOMER_INFO_START",
  FETCH_CUSTOMER_INFO_SUCCESS: "FETCH_CUSTOMER_INFO_SUCCESS",
  FETCH_CUSTOMER_INFO_FAILURE: "FETCH_CUSTOMER_INFO_FAILURE",

  FETCH_CUSTOMER_MORE_INFO_START: "FETCH_CUSTOMER_MORE_INFO_START",
  FETCH_CUSTOMER_MORE_INFO_SUCCESS: "FETCH_CUSTOMER_MORE_INFO_SUCCESS",

  FETCH_CUSTOMER_SLIDER_START: "FETCH_CUSTOMER_SLIDER_START",
  FETCH_CUSTOMER_SLIDER_SUCCESS: "FETCH_CUSTOMER_SLIDER_SUCCESS",

  FETCH_CUSTOMER_GALLERY_START: "FETCH_CUSTOMER_GALLERY_START",
  FETCH_CUSTOMER_GALLERY_SUCCESS: "FETCH_CUSTOMER_GALLERY_SUCCESS",

  CREATE_REZERVATION_SUCCESS: "CREATE_REZERVATION_SUCCESS",

  FETCH_PRICE_OF_AREA_START: "FETCH_PRICE_OF_AREA_START",
  FETCH_PRICE_OF_AREA_SUCCESS: "FETCH_PRICE_OF_AREA_SUCCESS",
};
export default CustomerActionTypes;
