const CategoryActionTypes = {
  FETCH_CATEGORIES_START: "FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  RESET_CATEGORIES: "RESET_CATEGORIES",
};
export default CategoryActionTypes;
