const MainActionTypes = {
  FETCH_CUSTOMERS_START: "FETCH_CUSTOMERS_START",
  FETCH_CUSTOMERS_SUCCESS: "FETCH_CUSTOMERS_SUCCESS",

  FETCH_CUISINES_START: "FETCH_CUISINES_START",
  FETCH_CUISINES_SUCCESS: "FETCH_CUISINES_SUCCESS",

  CHOOSE_CITY: "CHOOSE_CITY",
  CHOOSE_COUNTY: "CHOOSE_COUNTY",

  RESET_MAIN: "RESET_MAIN",

  LEAVE_RESTAURANT_PAGE: "LEAVE_RESTAURANT_PAGE",

  FETCH_USER_ORDERS_START: "FETCH_USER_ORDERS_START",
  FETCH_USER_ORDERS_SUCCESS: "FETCH_USER_ORDERS_SUCCESS",
};
export default MainActionTypes;
