const MainActionTypes = {
  FETCH_CUSTOMERS_START: "FETCH_CUSTOMERS_START",
  FETCH_CUSTOMERS_SUCCESS: "FETCH_CUSTOMERS_SUCCESS",

  FETCH_CUISINES_START: "FETCH_CUISINES_START",
  FETCH_CUISINES_SUCCESS: "FETCH_CUISINES_SUCCESS",

  CHOOSE_CITY: "CHOOSE_CITY",
};
export default MainActionTypes;
