const LikeActionTypes = {
  FETCH_COMMENT_LIKES_START: "FETCH_COMMENT_LIKES_START",
  FETCH_COMMENT_LIKES_SUCCESS: "FETCH_COMMENT_LIKES_SUCCESS",

  ADD_LIKE_SUCCESS: "ADD_LIKE_SUCCESS",
  UPDATE_LIKE_SUCCESS: "UPDATE_LIKE_SUCCESS",
  DELETE_LIKE_SUCCESS: "DELETE_LIKE_SUCCESS",
};
export default LikeActionTypes;
