const OrderActionTypes = {
  FETCH_ORDER_DETAIL_START: "FETCH_ORDER_DETAIL_START",
  FETCH_ORDER_DETAIL_SUCCESS: "FETCH_ORDER_DETAIL_SUCCESS",

  FETCH_USER_ORDER_HISTORY_START: "FETCH_USER_ORDER_HISTORY_START",
  FETCH_USER_ORDER_HISTORY_SUCCESS: "FETCH_USER_ORDER_HISTORY_SUCCESS",
};
export default OrderActionTypes;
