const OrderActionTypes = {
  FETCH_ORDER_DETAIL_START: "FETCH_ORDER_DETAIL_START",
  FETCH_ORDER_DETAIL_SUCCESS: "FETCH_ORDER_DETAIL_SUCCESS",

  FETCH_USER_ORDER_HISTORY_START: "FETCH_USER_ORDER_HISTORY_START",
  FETCH_USER_ORDER_HISTORY_SUCCESS: "FETCH_USER_ORDER_HISTORY_SUCCESS",

  FETCH_PAYMENT_METHODS_START: "FETCH_PAYMENT_METHODS_START",
  FETCH_PAYMENT_METHODS_SUCCESS: "FETCH_PAYMENT_METHODS_SUCCESS",

  CHOOSE_ADDRESS: "CHOOSE_ADDRESS",
  CHOOSE_PAYMENT_METHOD: "CHOOSE_PAYMENT_METHOD",

  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",

  RESET_ORDERS: "RESET_ORDERS",
};
export default OrderActionTypes;
