const OrderActionTypes = {
  FETCH_ORDER_DETAIL_START: "FETCH_ORDER_DETAIL_START",
  FETCH_ORDER_DETAIL_SUCCESS: "FETCH_ORDER_DETAIL_SUCCESS",

  FETCH_USER_ORDER_HISTORY_START: "FETCH_USER_ORDER_HISTORY_START",
  FETCH_USER_ORDER_HISTORY_SUCCESS: "FETCH_USER_ORDER_HISTORY_SUCCESS",

  FETCH_PAYMENT_METHODS_START: "FETCH_PAYMENT_METHODS_START",
  FETCH_PAYMENT_METHODS_SUCCESS: "FETCH_PAYMENT_METHODS_SUCCESS",

  CHOOSE_ADDRESS: "CHOOSE_ADDRESS",
  CHOOSE_PAYMENT_METHOD: "CHOOSE_PAYMENT_METHOD",
};
export default OrderActionTypes;
