const CommentActionTypes = {
  FETCH_CUSTOMER_COMMENTS_START: "FETCH_CUSTOMER_COMMENTS_START",
  FETCH_CUSTOMER_COMMENTS_SUCCESS: "FETCH_CUSTOMER_COMMENTS_SUCCESS",
  SEE_ALL_COMMENTS: "SEE_ALL_COMMENTS",
};
export default CommentActionTypes;
