const UserActionTypes = {
  FETCH_USER_INFO_START: "FETCH_USER_INFO_START",
  FETCH_USER_INFO_SUCCESS: "FETCH_USER_INFO_SUCCESS",

  FETCH_USER_ADDRESSES_START: "FETCH_USER_ADDRESSES_START",
  FETCH_USER_ADDRESSES_SUCCESS: "FETCH_USER_ADDRESSES_SUCCESS",

  FETCH_FAVORITE_PRODUCTS_START: "FETCH_FAVORITE_PRODUCTS_START",
  FETCH_FAVORITE_PRODUCTS_SUCCESS: "FETCH_FAVORITE_PRODUCTS_SUCCESS",

  EDIT_PROFILE_START: "EDIT_PROFILE_START",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAIL: "EDIT_PROFILE_FAIL",
};
export default UserActionTypes;
