const UserActionTypes = {
  FETCH_USER_INFO_START: "FETCH_USER_INFO_START",
  FETCH_USER_INFO_SUCCESS: "FETCH_USER_INFO_SUCCESS",

  FETCH_USER_ADDRESSES_START: "FETCH_USER_ADDRESSES_START",
  FETCH_USER_ADDRESSES_SUCCESS: "FETCH_USER_ADDRESSES_SUCCESS",
};
export default UserActionTypes;
