const ProductActionTypes = {
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",

  FETCH_PRODUCT_MATERIAL_START: "FETCH_PRODUCT_MATERIAL_START",
  FETCH_PRODUCT_MATERIAL_SUCCESS: "FETCH_PRODUCT_MATERIAL_SUCCESS",
  FETCH_MENU_OPTIONS: "FETCH_MENU_OPTIONS",

  RESET_PRODUCTS: "RESET_PRODUCTS",
};
export default ProductActionTypes;
