//PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_MOST_POPULAR_PRODUCTS = "GET_MOST_POPULAR_PRODUCTS"

//CUSTOMERS
export const GET_CUSTOMER_INFO = "GET_CUSTOMER_INFO"
export const GET_CUSTOMER_MORE_INFO = "GET_CUSTOMER_MORE_INFO"

//USERS
export const GET_USER_ADDRESS = "GET_USER_ADDRESS"
export const GET_USER_OFFERS = "GET_USER_OFFERS"

export const GET_USER_INFO = "GET_USER_INFO"
export const GET_USER_FAVORITES_PRODUCT = "GET_USER_FAVORITES_PRODUCT"
export const GET_USER_ORDERS ="GET_USER_ORDERS"
//USER CARDS
export const GET_USER_CARDS = "GET_USER_CARDS"
export const DELETE_USER_CARDS = "DELETE_USER_CARDS"
