const AddressActionTypes = {
  FETCH_CITIES_START: "FETCH_CITIES_START",
  FETCH_CITIES_SUCCESS: "FETCH_CITIES_SUCCESS",

  FETCH_COUNTIES_START: "FETCH_COUNTIES_START",
  FETCH_COUNTIES_SUCCESS: "FETCH_COUNTIES_SUCCESS",

  FETCH_AREAS_START: "FETCH_AREAS_START",
  FETCH_AREAS_SUCCESS: "FETCH_AREAS_SUCCESS",
};
export default AddressActionTypes;
